changelog:
  categories:
    - title: Breaking changes
      labels:
        - "Breaking change"
    - title: Bugfixes
      labels:
        - bug
    - title: Dependency upgrades
      labels:
        - dependencies
